

var photosArray = [
  {thumb: "thumb0.jpg", full: "full0.jpg", week: "Week 1", cutline:"Protest for Palestine", imageKeywords:["week 1","protest","palestine"]},
  {thumb: "thumb1.jpg", full: "full1.jpg", week: "Week 2", cutline:"Old lady resting on Market Street", imageKeywords:["week 2","lady","resting","bored"]},
  {thumb: "thumb2.jpg", full: "full2.jpg", week: "Week 3", cutline:"Reading outside a bar in the Tenderloin", imageKeywords:["week 3","reading","tenderloin"]},
  {thumb: "thumb3.jpg", full: "full3.jpg", week: "Week 4", cutline:"Hookah smokers Tenderloin", imageKeywords:["week 4","hookah","tenderloin"]},
  {thumb: "thumb4.jpg", full: "full4.jpg", week: "Week 5", cutline:"Smoke break Chinatown", imageKeywords:["chinatown","smoking","break"]},
  {thumb: "thumb5.jpg", full: "full5.jpg", week: "Week 5", cutline:"Smoke break Chinatown", imageKeywords:["chinatown","smoking","break"]},
  {thumb: "thumb6.jpg", full: "full6.jpg", week: "Week 6", cutline:"Tarot card reader in the Mission", imageKeywords:["tarot card","mission","psychic"]},
  {thumb: "thumb7.jpg", full: "full7.jpg", week: "Week 7", cutline:"Street scene in the Tenderloin", imageKeywords:["street","tenderloin"]},
  {thumb: "thumb8.jpg", full: "full8.jpg", week: "Week 7", cutline:"Posing with monks in Chinatown", imageKeywords:["monks","chinatown","tourists"]},
  {thumb: "thumb9.jpg", full: "full9.jpg", week: "Week 8", cutline:"Rough night in the Castro", imageKeywords:["castro","junkie","drugs"]},
  {thumb: "thumb10.jpg", full: "full10.jpg", week: "Week 8", cutline:"Guitar player in the Mission District", imageKeywords:["mission","guitar"]},
  {thumb: "thumb11.jpg", full: "full11.jpg", week: "Week 8", cutline:"Game of catch while waiting for the train", imageKeywords:["muni","football","church"]},
  {thumb: "thumb12.jpg", full: "full12.jpg", week: "Week 9", cutline:"Folsom Street Fair", imageKeywords:["folsom street fair"]},
  {thumb: "thumb13.jpg", full: "full13.jpg", week: "Week 10", cutline:"Chatting with ambulance drivers near Fisherman's Wharf", imageKeywords:["ambulance","injured","homeless"]},
  {thumb: "thumb14.jpg", full: "full14.jpg", week: "Week 11", cutline:"A woman resting near Union Square", imageKeywords:["resting","union Square"]},
  {thumb: "thumb15.jpg", full: "full15.jpg", week: "Week 12", cutline:"Sailors take in the sites during Fleet Week", imageKeywords:["sailors","fleet week"]},
  {thumb: "thumb16.jpg", full: "full16.jpg", week: "Week 13", cutline:"Runners run through the Tenderloin during the Nike Marathon", imageKeywords:["runners","marathon","running","nike"]},
  {thumb: "thumb17.jpg", full: "full17.jpg", week: "Week 14", cutline:"Blanket man near Polk Street", imageKeywords:["blanket","polk"]},
  {thumb: "thumb18.jpg", full: "full18.jpg", week: "Week 15", cutline:"Dia de los Muerto San Francisco", imageKeywords:["dia de los muerto","mission","day of dead"]},
  {thumb: "thumb19.jpg", full: "full19.jpg", week: "Week 15", cutline:"Halloween in the Mission ", imageKeywords:["halloween","mission","red"]},
  {thumb: "thumb20.jpg", full: "full20.jpg", week: "Week 15", cutline:"A fan watches game 7 of the World Series on a giant screen set up at SF City Hall", imageKeywords:["giants","world series","baseball"]},
  {thumb: "thumb21.jpg", full: "full21.jpg", week: "Week 15", cutline:"Fans watches game 7 of the World Series on a giant screen set up at SF City Hall ", imageKeywords:["giants","world series","baseball"]},
  {thumb: "thumb22.jpg", full: "full22.jpg", week: "Week 15", cutline:"Giant's fans celebrate the team's third World Series championship", imageKeywords:["giants","world series","baseball"]},
  {thumb: "thumb23.jpg", full: "full23.jpg", week: "Week 15", cutline:"Giant's fan takes a photo with SF's finest follow the Giant's thire World Series championship", imageKeywords:["giants","world series","baseball","police"]},
  {thumb: "thumb24.jpg", full: "full24.jpg", week: "Week 15", cutline:"Giant's victory parade", imageKeywords:["giants", "parade", "world series"]},
  {thumb: "thumb25.jpg", full: "full25.jpg", week: "Week 15", cutline:"Giant's fans celebrate the team's third World Series championship", imageKeywords:["giants", "parade","world series"]},
  {thumb: "thumb26.jpg", full: "full26.jpg", week: "Week 16", cutline:"Cowboy rests before the start of San Francisco's annual Veteran's Day Parade", imageKeywords:["cowboy","horses","parade","veterans"]},
  {thumb: "thumb27.jpg", full: "full27.jpg", week: "Week 16", cutline:"Mayor Ed Lee shares a laugh before the start of annual Veteran's Day Parade", imageKeywords:["mayor", "ed", "lee"]},
  {thumb: "thumb28.jpg", full: "full28.jpg", week: "Week 17", cutline:"Beauty kills on Market Street", imageKeywords:["beauty", "fashion", "tattoo"]},
  {thumb: "thumb29.jpg", full: "full29.jpg", week: "Week 18", cutline:"Repent at the Powell Street turnaround", imageKeywords:["preacher", "sign"]},
  {thumb: "thumb30.jpg", full: "full30.jpg", week: "Week 18", cutline:"Bar security guard in Chinatown", imageKeywords:["chinatown", "bar","security"]},
  {thumb: "thumb31.jpg", full: "full31.jpg", week: "Week 19", cutline:"Black Lives Matter protestors make their way down Market Street", imageKeywords:["black","black lives matter","protest"]},
  {thumb: "thumb32.jpg", full: "full32.jpg", week: "Week 19", cutline:"Riot police at Union Square", imageKeywords:["police", "riot", "protest"]},
  {thumb: "thumb33.jpg", full: "full33.jpg", week: "Week 20", cutline:"Caution buses make wide right turns", imageKeywords:["sutter street", "bus", "accident"]},
  {thumb: "thumb34.jpg", full: "full34.jpg", week: "Week 21", cutline:"Black Lives Matter protestor on Market Street", imageKeywords:["black lives matter", "protest", "market"]},
  {thumb: "thumb35.jpg", full: "full35.jpg", week: "Week 21", cutline:"A protestor prepares to be transported to jail follow a Black Lives Matter protest at SF City Hall", imageKeywords:["police", "protest", "arrest"]},
  {thumb: "thumb36.jpg", full: "full36.jpg", week: "Week 22", cutline:"Ambulance workers prepare to transfer a homeless person to the hospital. They put a mesh cover over his face because he kept spitting on them", imageKeywords:["homeless", "ambulance", "spitter"]},
  {thumb: "thumb37.jpg", full: "full37.jpg", week: "Week 23", cutline:"Surfer at Steamer's Lane in Santa Cruz", imageKeywords:["surfer", "santa cruz", "ocean"]},
  {thumb: "thumb38.jpg", full: "full38.jpg", week: "Week 24", cutline:"Girls take a selfie to ring in the New Year", imageKeywords:["selfie", "new year", "girls"]},
  {thumb: "thumb39.jpg", full: "full39.jpg", week: "Week 25", cutline:"A couple participating in 'No Pants Day' walks in the Mission", imageKeywords:["no pants", "mission", "couple"]},
  {thumb: "thumb40.jpg", full: "full40.jpg", week: "Week 25", cutline:"'No pants Day' particpants in the Mission", imageKeywords:["no pants", "mission", "dance"]},
  {thumb: "thumb41.jpg", full: "full41.jpg", week: "Week 26", cutline:"Homeless near Sixth Street", imageKeywords:["sixth street", "6th","homeless"]},
  {thumb: "thumb42.jpg", full: "full42.jpg", week: "Week 26", cutline:"A homeless person sleeps on the Market Street sidewalk", imageKeywords:["sleep", "homeless", "market street"]},
  {thumb: "thumb43.jpg", full: "full43.jpg", week: "Week 26",cutline:"Waiting for the bus on Market Street", imageKeywords:["portrait", "market street", "purple"]},
  {thumb: "thumb44.jpg", full: "full44.jpg", week: "Week 27",cutline:"Woman smoking near Union Square", imageKeywords:["smoking", "portrait", "union square"]},
  {thumb: "thumb45.jpg", full: "full45.jpg", week: "Week 27",cutline:"This woman hates communists in Chinatown", imageKeywords:["chinatown", "communist", "protest"]},
  {thumb: "thumb46.jpg", full: "full46.jpg", week: "Week 28",cutline:"woman being handcuffed following a protest against San Francisco anti-nudity ordinance", imageKeywords:["naked", "protest", "naked", "arrested"]},
  {thumb: "thumb47.jpg", full: "full47.jpg", week: "Week 29",cutline:"A man has trouble with his walker near the Powell Street BART station", imageKeywords:["powell", "walker"]},
  {thumb: "thumb48.jpg", full: "full48.jpg", week: "Week 30",cutline:"Portrait of a homeless man above the Stockton Street Tunnel", imageKeywords:["portrait", "homeless"]},
  {thumb: "thumb49.jpg", full: "full49.jpg", week: "Week 30",cutline:"Having fun at the annual Valetine Day's pillow fight near the Ferry Building", imageKeywords:["pillow", "fight", "valentine"]},
  {thumb: "thumb50.jpg", full: "full50.jpg", week: "Week 30",cutline:"On their way to the Valentine's Day cotillion", imageKeywords:["valentine", "cotillion", "dance", "party"]},
  {thumb: "thumb51.jpg", full: "full51.jpg", week: "Week 31",cutline:"Midnight in Chinatown at the start of Chinese New Year", imageKeywords:["chinatown", "fireworks", "chinese", "new year"]},
  {thumb: "thumb52.jpg", full: "full52.jpg", week: "Week 32",cutline:"Police questioning suspects near Union Square", imageKeywords:["police", "sfpd", "arrest", "handcuffed"]},
  {thumb: "thumb53.jpg", full: "full53.jpg", week: "Week 32",cutline:"Johnny Rock and Roll in the Mission District", imageKeywords:["rock", "mission", "guitar", "rock and roll"]},
  {thumb: "thumb54.jpg", full: "full54.jpg", week: "Week 33",cutline:"Kids waiting for the start of the Chinese New Years Parade", imageKeywords:["parade", "chinese", "new year"]},
  {thumb: "thumb55.jpg", full: "full55.jpg", week: "Week 33",cutline:"Band members take a break before the start of San Francisco's annual Chinese New Year Parade", imageKeywords:["parade", "chinese", "band"]},
  {thumb: "thumb56.jpg", full: "full56.jpg", week: "Week 34",cutline:"Girls texting following a rave", imageKeywords:["texting", "rave", "phones"]},
  {thumb: "thumb57.jpg", full: "full57.jpg", week: "Week 35",cutline:"Aztec dancers in the Mission District", imageKeywords:["aztec", "mission", "dance","dancer"]},
  {thumb: "thumb58.jpg", full: "full58.jpg", week: "Week 35",cutline:"Aztec dancer in the Mission District", imageKeywords:["dancer", "aztec", "mission"]},
  {thumb: "thumb59.jpg", full: "full59.jpg", week: "Week 36",cutline:"Playing poker in Chinatown", imageKeywords:["cards", "poker", "chinatown"]},
  {thumb: "thumb60.jpg", full: "full60.jpg", week: "Week 37",cutline:"Big Wheel riders make their way down Vermont Street during the annual Easter Big Wheel ride", imageKeywords:["big Wheel", "tricycle", "easter"]},
  {thumb: "thumb61.jpg", full: "full61.jpg", week: "Week 37",cutline:"Playing the drums during the annual April first Saint Stupid's Day Parade.", imageKeywords:["april 1st", "saint stupid", "parade"]},
  {thumb: "thumb62.jpg", full: "full62.jpg", week: "Week 37",cutline:"Leading the annual April first Saint Stupid's Day Parade.", imageKeywords:["april 1st", "saint stupid", "parade"]},
  {thumb: "thumb63.jpg", full: "full63.jpg", week: "Week 37",cutline:"Fire dancer at the Embarcadero", imageKeywords:["fire", "dancer", "twiller"]},
  {thumb: "thumb64.jpg", full: "full64.jpg", week: "Week 38",cutline:"An old man walking through Chinatown", imageKeywords:["chinatown", "old"]},
  {thumb: "thumb65.jpg", full: "full65.jpg", week: "Week 39",cutline:"Dancing at the Indian Holi Day festival", imageKeywords:["holi", "color", "festival"]},
  {thumb: "thumb66.jpg", full: "full66.jpg", week: "Week 39",cutline:"Dancing at the Indian Holi Day festival", imageKeywords:["holi", "color", "festival"]},
  {thumb: "thumb67.jpg", full: "full67.jpg", week: "Week 40",cutline:"Homeless man at the Powell Street BART station", imageKeywords:["homeless", "wheelchair", "powell"]},
  {thumb: "thumb68.jpg", full: "full68.jpg", week: "Week 41",cutline:"Safe at home. The Giants lose one to the Padres", imageKeywords:["giants", "baseball", "padres"]},
  {thumb: "thumb69.jpg", full: "full69.jpg", week: "Week 42",cutline:"A bride and groom make their way up Haye's Hill during the annual Bay to Breakers race", imageKeywords:["bride", "groom", "running", "bay to Breakers", "race","runners"]},
  {thumb: "thumb70.jpg", full: "full70.jpg", week: "Week 42",cutline:"Left shark makes his way up Hayes Hill during the annual Bay to Breakers race", imageKeywords:["running", "bay to Breakers", "race", "left shark","runners"]},
  {thumb: "thumb71.jpg", full: "full71.jpg", week: "Week 43",cutline:"Ms Columbia dances during Carnaval in the Mission", imageKeywords:["columbia", "mission", "carnaval", "dance"]},
  {thumb: "thumb72.jpg", full: "full72.jpg", week: "Week 43",cutline:"Dancers at Carnaval in the Mission", imageKeywords:["mission", "dance","carnaval"]},
  {thumb: "thumb73.jpg", full: "full73.jpg", week: "Week 43",cutline:"Ms Columbia dances during Carnaval in the Mission", imageKeywords:["columbia", "mission", "carnaval", "dance"]},
  {thumb: "thumb74.jpg", full: "full74.jpg", week: "Week 43",cutline:"Dancing at the Mission District Carnaval", imageKeywords:["dancer", "mission", "carnival"]},
  {thumb: "thumb75.jpg", full: "full75.jpg", week: "Week 43",cutline:"Getting ready for the parade at the Mission District Carnaval", imageKeywords:["dancer", "mission", "carnival"]},
  {thumb: "thumb76.jpg", full: "full76.jpg", week: "Week 44",cutline:"Last call on Polk Street", imageKeywords:["polk", "leaning", "hydrant"]},
  {thumb: "thumb77.jpg", full: "full77.jpg", week: "Week 45",cutline:"Playing the accordion near the Stockton Street Tunnel", imageKeywords:["accordion", "stockton", "musician"]},
  {thumb: "thumb78.jpg", full: "full78.jpg", week: "Week 46",cutline:"Blessing of the animals in North Beach", imageKeywords:["blessing", "church", "north beach", "dogs"]},
  {thumb: "thumb79.jpg", full: "full79.jpg", week: "Week 46",cutline:"Blessing of the animals in North Beach", imageKeywords:["blessing", "church", "north beach", "dogs"]},
  {thumb: "thumb80.jpg", full: "full80.jpg", week: "Week 47",cutline:"Stephen Curry celebrates the Warrior's first NBA Championship in thirty years", imageKeywords:["warriors", "parade", "nba", "championship","curry"]},
  {thumb: "thumb81.jpg", full: "full81.jpg", week: "Week 48",cutline:"Gay Pride Parade revellers make their way down Market Street", imageKeywords:["gay", "pride", "parade"]},
  {thumb: "thumb82.jpg", full: "full82.jpg", week: "Week 48",cutline:"Gay Pride Parade revellers make their way down Market Street", imageKeywords:["gay", "pride", "parade"]},
  {thumb: "thumb83.jpg", full: "full83.jpg", week: "Week 48",cutline:"Gay Pride Parade revellers make their way down Market Street", imageKeywords:["gay", "pride", "parade"]},
  {thumb: "thumb84.jpg", full: "full84.jpg", week: "Week 48",cutline:"Gay Pride Parade seen through a cellphone", imageKeywords:["gay", "pride", "parade"]},
  {thumb: "thumb85.jpg", full: "full85.jpg", week: "Week 48",cutline:"Gay Pride Parade revellers make their way down Market Street", imageKeywords:["gay", "pride", "parade"]},
  {thumb: "thumb86.jpg", full: "full86.jpg", week: "Week 49",cutline:"Enjoying some music in the Tenderloin", imageKeywords:["tenderloin", "music"]},
  {thumb: "thumb87.jpg", full: "full87.jpg", week: "Week 49",cutline:"Woman in the Tenderloin", imageKeywords:["tenderloin", "woman", "smoking"]},
  {thumb: "thumb88.jpg", full: "full88.jpg", week: "Week 50",cutline:"Dancing during a block party in the Tenderloin", imageKeywords:["tenderloin", "block party", "dancing"]},
  {thumb: "thumb89.jpg", full: "full89.jpg", week: "Week 50",cutline:"Dancing during a block party in the Tenderloin", imageKeywords:["tenderloin", "block party", "dancing"]},
  {thumb: "thumb90.jpg", full: "full90.jpg", week: "Week 50",cutline:"Dancing during a block party in the Tenderloin", imageKeywords:["tenderloin", "block party", "dancing"]},
  {thumb: "thumb91.jpg", full: "full91.jpg", week: "Week 51",cutline:"Slam dancing at the F*ckfest punk rock festival in the Bay View District", imageKeywords:["punk", "rock", "music", "dance"]},
  {thumb: "thumb92.jpg", full: "full92.jpg", week: "Week 51",cutline:"Slam dancing at the F*ckfest punk rock festival in the Bay View District", imageKeywords:["punk", "rock", "music", "dance"]},
  {thumb: "thumb93.jpg", full: "full93.jpg", week: "Week 51",cutline:"Slam dancing at the F*ckfest punk rock festival in the Bay View District", imageKeywords:["punk", "rock", "music", "dance"]},
  {thumb: "thumb94.jpg", full: "full94.jpg", week: "Week 51",cutline:"Slam dancing at the F*ckfest punk rock festival in the Bay View District", imageKeywords:["punk", "rock", "music", "dance"]},
  {thumb: "thumb95.jpg", full: "full95.jpg", week: "Week 51",cutline:"Dancing at the F*ckfest punk rock festival in the Bay View District", imageKeywords:["punk", "rock", "music", "dance"]},
  {thumb: "thumb96.jpg", full: "full96.jpg", week: "Week 52",cutline:"World Naked Bike Ride near Fisherman's Wharf", imageKeywords:["bike", "fisherman's", "naked"]},
  {thumb: "thumb97.jpg", full: "full97.jpg", week: "Week 52",cutline:"World Naked Bike Riders take a break near the Bay Bridge", imageKeywords:["bike", "bridge", "naked", "bay"]},
  {thumb: "thumb98.jpg", full: "full98.jpg", week: "Week 52",cutline:"World Naked Bike Riders take a break near the Bay Bridge", imageKeywords:["bike", "bridge", "naked", "bay"]},
  {thumb: "thumb99.jpg", full: "full99.jpg", week: "Week 53",cutline:"Taking the dogs for a walk at Union Square", imageKeywords:["dogs", "dog", "union"]},
  {thumb: "thumb100.jpg", full: "full100.jpg", week: "Week 54",cutline:"Out for a spin on Sixth Street", imageKeywords:["sixth", "scooter", "smoking"]},
  {thumb: "thumb101.jpg", full: "full101.jpg", week: "Week 55",cutline:"Rescue workers transport a sick man to the hospital", imageKeywords:["ambulance", "elderly", "sick"]},
  {thumb: "thumb102.jpg", full: "full102.jpg", week: "Week 56",cutline:"A topless woman protesting the cities anti-nudity ordiance at Dolores Park", imageKeywords:["topless", "dolores", "park", "naked"]},
  {thumb: "thumb103.jpg", full: "full103.jpg", week: "Week 57",cutline:"Kissing couple in North Beach", imageKeywords:["kissing", "couple", "north","beach"]},
  {thumb: "thumb104.jpg", full: "full104.jpg", week: "Week 58",cutline:"A policeman looks on as revellers make their way down Market Street during 'Leather Walk'", imageKeywords:["naked", "police", "castro","leather"]},
  {thumb: "thumb105.jpg", full: "full105.jpg", week: "Week 58",cutline:"'Leather Walk' participant in the Castro", imageKeywords:["castro", "leather", "portrait"]},
  {thumb: "thumb106.jpg", full: "full106.jpg", week: "Week 59",cutline:"Portait at the Folsom Street Fair", imageKeywords:["folsom", "fair", "leather"]},
  {thumb: "thumb107.jpg", full: "full107.jpg", week: "Week 59",cutline:"Lowrider competition San Francisco", imageKeywords:["lowrider", "cars"]},
  {thumb: "thumb108.jpg", full: "full108.jpg", week: "Week 59",cutline:"Lowrider competition San Francisco", imageKeywords:["lowrider", "cars"]},
  {thumb: "thumb109.jpg", full: "full109.jpg", week: "Week 59",cutline:"Knights of Columbus Parade through North Beach", imageKeywords:["parade", "north beach", "knights", "columbus"]},
  {thumb: "thumb110.jpg", full: "full110.jpg", week: "Week 60",cutline:"A preist blessing the fishing fleet following the Columbus Day Parade", imageKeywords:["bless", "fishing", "preist","blessing"]},
  {thumb: "thumb111.jpg", full: "full111.jpg", week: "Week 60",cutline:"The Blue Angels perform during Fleet Week", imageKeywords:["planes", "airplanes", "jets","blue","angels","fleet"]},
  {thumb: "thumb112.jpg", full: "full112.jpg", week: "Week 61",cutline:"Hip hop performer in the Mission", imageKeywords:["hip hop", "mission", "music"]},
  {thumb: "thumb113.jpg", full: "full113.jpg", week: "Week 62",cutline:"Girls play on the archery sculpture near the Bay Bridge", imageKeywords:["archery", "girls", "bay"]},
  {thumb: "thumb114.jpg", full: "full114.jpg", week: "Week 64",cutline:"Critical mass rider during the halloween ride", imageKeywords:["halloween", "bike", "critical","mass"]},
  {thumb: "thumb115.jpg", full: "full115.jpg", week: "Week 64",cutline:"Halloween in the Mission District", imageKeywords:["halloween", "mission", "bunny"]},
  {thumb: "thumb116.jpg", full: "full116.jpg", week: "Week 64",cutline:"Lion checks his phone during Halloween in the Mission District", imageKeywords:["halloween", "mission", "lion","phone"]},
  {thumb: "thumb117.jpg", full: "full117.jpg", week: "Week 64",cutline:"Bunny pimp celebrates Halloween in the Mission District", imageKeywords:["halloween", "mission", "bunny","pimp"]},
  {thumb: "thumb118.jpg", full: "full118.jpg", week: "Week 64",cutline:"Halloween in the Mission District", imageKeywords:["halloween", "mission", "scary"]},
  {thumb: "thumb119.jpg", full: "full119.jpg", week: "Week 64",cutline:"Halloween in the Mission District", imageKeywords:["halloween", "mission", "skeleton"]},
  {thumb: "thumb120.jpg", full: "full120.jpg", week: "Week 64",cutline:"Bunny man in the Mission District", imageKeywords:["bunny", "mission"]},
  {thumb: "thumb121.jpg", full: "full121.jpg", week: "Week 64",cutline:"Waiting for the start of the Veteran's Day Parade", imageKeywords:["parade", "veterans"]},
  {thumb: "thumb122.jpg", full: "full122.jpg", week: "Week 65",cutline:"An Air Force band member plays the saxophone prior to the start of San Francisco's annual Veteran's Day Parade", imageKeywords:["band", "veterans","parade","music","saxophone"]},
  {thumb: "thumb123.jpg", full: "full123.jpg", week: "Week 65",cutline:"Veterans March in the annual Veteran's Day Parade", imageKeywords:["soldiers", "veterans", "march"]},
  {thumb: "thumb124.jpg", full: "full124.jpg", week: "Week 66",cutline:"A young girl lights candles in front of the SF French Consulate following the Paris attacks", imageKeywords:["paris", "memorial", "candles","girl"]},
  {thumb: "thumb125.jpg", full: "full125.jpg", week: "Week 67",cutline:"Train ride through the Castro District", imageKeywords:["castro", "train"]},
  {thumb: "thumb126.jpg", full: "full126.jpg", week: "Week 68",cutline:"Dianne on a cold day in the tenderloin", imageKeywords:["cold", "homeless", "dianne"]},
  {thumb: "thumb127.jpg", full: "full127.jpg", week: "Week 68",cutline:"Santas at Union Square wait for the start of Santacon", imageKeywords:["santa", "santacon", "christmas"]},
  {thumb: "thumb128.jpg", full: "full128.jpg", week: "Week 69",cutline:"Picture with semi-naked guys during SantaCon at Union Square", imageKeywords:["santa", "santacon", "christmas","naked"]},
  {thumb: "thumb129.jpg", full: "full129.jpg", week: "Week 69",cutline:"Posing with San Francisco policeman during Santacon at Union Square", imageKeywords:["santacon", "police", "christmas"]},
  {thumb: "thumb130.jpg", full: "full130.jpg", week: "Week 69",cutline:"Christmas run through the Castro District", imageKeywords:["castro", "run", "santa"]},
  {thumb: "thumb131.jpg", full: "full131.jpg", week: "Week 69",cutline:"Lightsaber dual commerating the premiere of the new Star Wars movie", imageKeywords:["lightsaber", "star", "star wars"]},
  {thumb: "thumb132.jpg", full: "full132.jpg", week: "Week 70",cutline:"Lightsaber dual commerating the premiere of the new Star Wars movie", imageKeywords:["lightsaber", "star", "star wars"]},
  {thumb: "thumb133.jpg", full: "full133.jpg", week: "Week 70",cutline:"Fireworks above the Ferry Building usher in 2016 during the annual New Year celebration", imageKeywords:["fireworks", "ferry", "new year"]},
  {thumb: "thumb134.jpg", full: "full134.jpg", week: "Week 71",cutline:"Late night in the Tenderloin", imageKeywords:["tenderloin"]},
  {thumb: "thumb135.jpg", full: "full135.jpg", week: "Week 72",cutline:"A rainy night on Polk Street", imageKeywords:["rain", "umbrella", "polk"]}
];
